language: julia
os:
  - linux
  - osx
julia:
  - 1.1
notifications:
  email: false
branches:
  only:
  - master
  - /release-.*/
after_success:
  # push coverage results to Codecov
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate()'
        - julia --project=docs/ --color=yes docs/make.jl
      after_success: skip
