language: julia
os:
  - linux
  - osx
julia:
  - 0.6
notifications:
  email: false
branches:
  only:
  - master
  - /release-.*/
script:
  - julia -e 'Pkg.add("Mimi")'
  - julia -e 'Pkg.add("CSVFiles")'
  - julia --code-coverage=user test/runtests.jl
after_success:
  # push coverage results to Codecov
  - julia -e 'Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'include("docs/make.jl")'
